server:
  port: 8080

spring:
  application:
    name: virtual-power-plant

  # 数据源配置由 DatabaseConfig 类管理，从 SecretConfigManager 获取配置

# MyBatis配置
mybatis:
  # Mapper XML文件位置
  mapper-locations: classpath:mapper/*.xml
  # 实体类包路径
  type-aliases-package: com.virtualpowerplant.model
  # MyBatis配置
  configuration:
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 开启延迟加载
    lazy-loading-enabled: true
    # 开启二级缓存
    cache-enabled: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# 日志配置
logging:
  level:
    com.virtualpowerplant.mapper: info
    org.springframework.jdbc: info